In [ ]:
# A. Calculation - Basic Calculation in Python
print("=== A. Basic Calculations ===")

# Addition
print("5 + 3 =", 5 + 3)

# Subtraction
print("10 - 4 =", 10 - 4)

# Multiplication
print("7 * 6 =", 7 * 6)

# Division
print("15 / 4 =", 15 / 4)

# Integer Division
print("15 // 4 =", 15 // 4)

# Modulus
print("15 % 4 =", 15 % 4)

# Exponentiation
print("2 ** 5 =", 2 ** 5)

# Order of operations
print("(5 + 3) * 2 =", (5 + 3) * 2)

print ((10 + 5) * (20 - 7) / 3)
print(2 ** 3 + 5 * 4)

=== A. Basic Calculations ===
5 + 3 = 8
10 - 4 = 6
7 * 6 = 42
15 / 4 = 3.75
15 // 4 = 3
15 % 4 = 3
2 ** 5 = 32
(5 + 3) * 2 = 16
65.0
28

Latihan:

Hitung (10 + 5) * (20 - 7) / 3

Berapa hasil 2 ** 3 + 5 * 4?

In [ ]:
# B. Data Types
print("\n=== B. Data Types ===")

# 1. Character (String in Python)
char_var = 'a'
string_var = "Hello Python"
print("\nCharacter/String:")
print(char_var, type(char_var))
print(string_var, type(string_var))

# Numeric - Integer
int_var = 25
print("\nInteger:")
print(int_var, type(int_var))

# Numeric - Float
float_var = 3.14159
print("\nFloat:")
print(float_var, type(float_var))

# Logical (Boolean in Python)
bool_var1 = True
bool_var2 = False
print("\nBoolean:")
print(bool_var1, type(bool_var1))
print(bool_var2, type(bool_var2))
print("5 > 3:", 5 > 3)

# Complex
complex_var = 3 + 4j
print("\nComplex:")
print(complex_var, type(complex_var))
print("Real part:", complex_var.real)
print("Imaginary part:", complex_var.imag)

=== B. Data Types ===

Character/String:
a <class 'str'>
Hello Python <class 'str'>

Integer:
25 <class 'int'>

Float:
3.14159 <class 'float'>

Boolean:
True <class 'bool'>
False <class 'bool'>
5 > 3: True

Complex:
(3+4j) <class 'complex'>
Real part: 3.0
Imaginary part: 4.0

Latihan:

Buat variabel harga = 15000 dan jumlah = 3, lalu hitung total harga.

Cek apakah 10 + 5 == 15 menghasilkan True atau False.

In [ ]:
harga = 15000
jumlah = 3
total_harga = harga * jumlah
print("Total harga:", total_harga)

print("10 + 5 == 15:", 10 + 5 == 15)

Total harga: 45000
10 + 5 == 15: True

In [ ]:
# C. Data Structures
print("\n=== C. Data Structures ===")

# 1. List (ordered, mutable, allows duplicates)
print("\n1. Lists:")
my_list = [1, 2, 3, 'apple', 'banana', True]
print("Original list:", my_list)
print("Type:", type(my_list))

# List operations
my_list.append('orange')  # Add item
print("After append:", my_list)
my_list.remove(2)  # Remove item
print("After remove:", my_list)
print("Index 3:", my_list[3])  # Access by index
my_list[1] = 'pear'  # Modify item
print("After modification:", my_list)

=== C. Data Structures ===

1. Lists:
Original list: [1, 2, 3, 'apple', 'banana', True]
Type: <class 'list'>
After append: [1, 2, 3, 'apple', 'banana', True, 'orange']
After remove: [1, 3, 'apple', 'banana', True, 'orange']
Index 3: banana
After modification: [1, 'pear', 'apple', 'banana', True, 'orange']

In [ ]:
# 2. Tuple (ordered, immutable, allows duplicates)
print("\n2. Tuples:")
my_tuple = (1, 3, 5, 'apple', 'banana')
print("Original tuple:", my_tuple)
print("Type:", type(my_tuple))

# Tuple operations
print("Index 2:", my_tuple[2])  # Access by index
print("Length:", len(my_tuple))
# my_tuple[1] = 'pear'  # This would raise an error as tuples are immutable

# Tuple unpacking
a, b, c, d, e = my_tuple
print("Unpacked:", a, b, c, d, e)

2. Tuples:
Original tuple: (1, 3, 5, 'apple', 'banana')
Type: <class 'tuple'>
Index 2: 5
Length: 5
Unpacked: 1 3 5 apple banana

In [ ]:
# 3. Set (unordered, mutable, no duplicates)
print("\n3. Sets:")
my_set = {1, 2, 3, 4, 4, 2, 'apple'}
print("Original set:", my_set)  # Duplicates are automatically removed
print("Type:", type(my_set))

# Set operations
my_set.add('banana')  # Add element
print("After add:", my_set)
my_set.remove(2)  # Remove element
print("After remove:", my_set)

# Set operations
other_set = {3, 4, 5, 'pear'}
print("Union:", my_set.union(other_set))
print("Intersection:", my_set.intersection(other_set))

3. Sets:
Original set: {1, 2, 3, 4, 'apple'}
Type: <class 'set'>
After add: {1, 2, 3, 4, 'banana', 'apple'}
After remove: {1, 3, 4, 'banana', 'apple'}
Union: {1, 3, 4, 5, 'pear', 'banana', 'apple'}
Intersection: {3, 4}

In [ ]:
# 4. Dictionary (key-value pairs, unordered, mutable)
print("\n4. Dictionaries:")
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}
print("Original dictionary:", my_dict)
print("Type:", type(my_dict))

# Dictionary operations
print("Name:", my_dict['name'])  # Access by key
my_dict['age'] = 31  # Modify value
print("After modification:", my_dict)
my_dict['job'] = 'Engineer'  # Add new key-value pair
print("After adding:", my_dict)
del my_dict['city']  # Remove key-value pair
print("After deletion:", my_dict)

4. Dictionaries:
Original dictionary: {'name': 'John', 'age': 30, 'city': 'New York'}
Type: <class 'dict'>
Name: John
After modification: {'name': 'John', 'age': 31, 'city': 'New York'}
After adding: {'name': 'John', 'age': 31, 'city': 'New York', 'job': 'Engineer'}
After deletion: {'name': 'John', 'age': 31, 'job': 'Engineer'}

In [ ]:
# 5. Vector (in Python, we typically use lists or numpy arrays)
print("\n5. Vectors:")
# Using lists as vectors
vector = [1, 2, 3, 4, 5]
print("Vector as list:", vector)

# Vector operations
# Element-wise addition
vector2 = [6, 7, 8, 9, 10]
added = [v1 + v2 for v1, v2 in zip(vector, vector2)]
print("Element-wise addition:", added)

# Scalar multiplication
scalar = 2
multiplied = [x * scalar for x in vector]
print("Scalar multiplication:", multiplied)

5. Vectors:
Vector as list: [1, 2, 3, 4, 5]
Element-wise addition: [7, 9, 11, 13, 15]
Scalar multiplication: [2, 4, 6, 8, 10]

In [ ]:
# Matrices (2D lists or numpy arrays)
print("\n6. Matrices:")
# Using list of lists
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print("Matrix:")
for row in matrix:
    print(row)

# Matrix operations
# Accessing elements
print("Element at row 1, column 2:", matrix[1][2])

# Transposing matrix
transposed = [[row[i] for row in matrix] for i in range(len(matrix[0]))]
print("\nTransposed matrix:")
for row in transposed:
    print(row)

6. Matrices:
Matrix:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Element at row 1, column 2: 6

Transposed matrix:
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]

In [ ]:
# Arrays (using numpy for efficient numerical operations)
import numpy as np

print("\n7. Arrays with NumPy:")
# Creating numpy arrays
arr = np.array([1, 2, 3, 4, 5])
print("1D array:", arr)
print("Type:", type(arr))

# 2D array
matrix_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("\n2D array:")
print(matrix_np)

# Array operations
print("\nArray operations:")
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Matrix multiplication:")
print(np.dot(matrix_np, matrix_np))

7. Arrays with NumPy:
1D array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array operations:
Sum: 15
Mean: 3.0
Matrix multiplication:
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

Latihan:

Buat list angka = [5, 2, 8, 1], lalu urutkan dengan .sort().

Buat dictionary motor = {"merk": "Honda", "cc": 150}, lalu tambahkan "warna": "merah".

In [ ]:
angka = [5,2,8,1]
angka.sort()
angka

[1, 2, 5, 8]

In [ ]:
motor = {"merk": "Honda", "cc": 150}
motor["warna"] = "merah"
motor

{'merk': 'Honda', 'cc': 150, 'warna': 'merah'}